version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: 'kfk'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  apiServer:
    container_name: 'apiServer'
    image: 'node:latest'
    ports:
      - '49160:3000'
    build:
      context: ./server/
      dockerfile: Dockerfile
    entrypoint: ["node", "server.js"]
    environment:
      - KAFKA_BITNAMI_SERVER=kafka:9092
      - TOPIC_PRODUCER=mensaje-server
      - TOPIC_CONSUMER=mensaje-consumer
      - HOOK_SECRET=supersecretstring
      - GROUP_ID=group-id
    depends_on:
      - kafka
  worker:
    container_name: 'worker'
    image: 'node:latest'
    build:
      context: ./consumer/
      dockerfile: Dockerfile
    entrypoint: ["node", "consumer.js"]
    environment:
      - KAFKA_BITNAMI_SERVER=kafka:9092
      - TOPIC_PRODUCER=mensaje-consumer
      - TOPIC_CONSUMER=mensaje-server
      - HOOK_SECRET=supersecretstring
      - GROUP_ID=group-id
    depends_on:
      - kafka