version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: 'kfk'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  apiServer:
    container_name: 'apiServer'
    image: 'node:latest'
    ports:
      - '49160:3000'
    build:
      context: .
      dockerfile: Dockerfile_Server
    entrypoint: ["node", "server.js"]
    environment:
      - KAFKA_BITNAMI_SERVER=kafka:9092
      - TOPIC_JOB_SENDED=job-send
      - TOPIC_JOB_RESULT=job-result
      - TOPIC_JOB_STATUS=job-status
      - KEYCLOAK_SERVER=http://keycloak:8080
      - KEYCLOAK_CLIENT_SECRET=TREsL7e4ZzMfr2BB0ofDuztv691fBSP5
      - KEYCLOAK_CLIENT_ID=server
      - KEYCLOAK_REALM=my_realm
      - GROUP_ID=proyecto-git-server
    depends_on:
      - kafka
  consumer:
    image: 'node:latest'
    build:
      context: .
      dockerfile: Dockerfile_Consumer
    entrypoint: ["node", "consumer.js"]
    environment:
      - KAFKA_BITNAMI_SERVER=kafka:9092
      - TOPIC_JOB_RECEIVED=job-send
      - TOPIC_JOB_RESULT=job-result
      - TOPIC_JOB_STATUS=job-status
      - GROUP_ID=proyecto-git-consumer
      - CONSUMERS_NUMBER=2
    depends_on:
      - kafka
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: 'keycloak'
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin 
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/main-realm.json
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm --debug"


